### ISSUE TITLE
Meetup notice

### ISSUE THREAD

**Issue by dacresni** [OpenDataSTL/opendatastl.github.io#21]
as a visitor I want to see when we have our next meetup on our website so i don't have to go to another page

**Comment by blordcastillo** [comment]
To get the correct link for the api, go to https://secure.meetup.com/meetup_api/console/?path=/2/events and enter 8985132 for group_id, and upcoming for status. Show the Response and then copy the Signed URL (not the Request URL). I would also suggest a smaller number than 20 for the page (like 2 or 3). To get this on the website, we will need to build a dynamic widget in js/html.
