### ISSUE TITLE
Visible form to get Slack invite

### ISSUE THREAD

**Issue by eleanortutt** [OpenDataSTL/opendatastl.github.io#23]
We communicate a lot on Slack and we have a google form we can point to if people want Slack invites. Would be nice to incorporate a prettier form (formspree.io???) into site and possibly ask more "getting to know you" questions - interests, skills, etc. - depending on whether or not we ask that info elsewhere.

Current form:
https://docs.google.com/forms/d/1uk5aoBd60e4en4OIYBLli1ewrSY4h7xtAhMLSWO1v1U/viewform

**Comment by blordcastillo** [comment]
Test in progress with using slackin. Trying first with integration into post, but may want to move to using a subdomain (e.g. slack.opendatastl.org) pointed at https://arcane-ocean-6928.herokuapp.com/
